Resources:
  # ConnectionsTable:
  #   Type: AWS::DynamoDB::Table
  #   DeletionPolicy: Retain
  #   Properties:
  #     TableName: ${self:custom.tableNames.connections}
  #     BillingMode: PAY_PER_REQUEST
  #     AttributeDefinitions:
  #       - AttributeName: connectionId
  #         AttributeType: S
  #       - AttributeName: userId
  #         AttributeType: S
  #     KeySchema:
  #       - AttributeName: connectionId
  #         KeyType: HASH
  #     GlobalSecondaryIndexes:
  #       - IndexName: UserIdIndex
  #         KeySchema:
  #           - AttributeName: userId
  #             KeyType: HASH
  #         Projection:
  #           ProjectionType: ALL
  #     TimeToLiveSpecification:
  #       AttributeName: ttl
  #       Enabled: true
  #     SSESpecification:
  #       SSEEnabled: true

  ConversationContextTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.context}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: conversationId
          AttributeType: S
      KeySchema:
        - AttributeName: conversationId
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: ttl
        Enabled: true
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  TokenUsageTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.tokens}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true

  HandoffQueueTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: ${self:custom.tableNames.handoff}
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: queueId
          AttributeType: S
        - AttributeName: status
          AttributeType: S
      KeySchema:
        - AttributeName: queueId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: StatusIndex
          KeySchema:
            - AttributeName: status
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      SSESpecification:
        SSEEnabled: true
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: true