service: espectra-backend

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

resources:
  - ${file(cognito.yml)}

outputs:
  UserPoolId:
    Value: !Ref SpectraUserPool
    Export:
      Name: ${self:service}-${self:provider.stage}-user-pool-id
  
  UserPoolClientId:
    Value: !Ref SpectraUserPoolClient
    Export:
      Name: ${self:service}-${self:provider.stage}-user-pool-client-id