# --- WebSocket Functions ---
wsAuthorizer:
  handler: services/websocket/handlers/authorizer.handler
  name: ${self:custom.service}-${self:provider.stage}-websocket-authorizer
  role: !ImportValue ${self:custom.service}-${self:provider.stage}-lambda-role-arn
  vpc: null
  memorySize: 256
  timeout: 29
  environment:
    COGNITO_USER_POOL_ID: !ImportValue ${self:custom.service}-${self:provider.stage}-user-pool-id
    COGNITO_CLIENT_ID: !ImportValue ${self:custom.service}-${self:provider.stage}-user-pool-client-id

webSocketConnect:
  handler: services/websocket/handlers/connect.handler
  name: ${self:custom.service}-${self:provider.stage}-webSocketConnect
  role: !ImportValue ${self:custom.service}-${self:provider.stage}-lambda-role-arn
  vpc: null
  events:
    - websocket:
        route: $connect
        authorizer:
          name: wsAuthorizer
          identitySource:
            - 'route.request.querystring.Auth'
        websocketApi:
          id: !Ref WebSocketApi

webSocketDisconnect:
  handler: services/websocket/handlers/disconnect.handler
  name: ${self:custom.service}-${self:provider.stage}-webSocketDisconnect
  role: !ImportValue ${self:custom.service}-${self:provider.stage}-lambda-role-arn
  vpc: null
  events:
    - websocket:
        route: $disconnect
        websocketApi:
          id: !Ref WebSocketApi

webSocketMessage:
  handler: services/websocket/handlers/message.handler
  name: ${self:custom.service}-${self:provider.stage}-webSocketMessage
  role: !ImportValue ${self:custom.service}-${self:provider.stage}-lambda-role-arn
  vpc: null
  events:
    - websocket:
        route: $default
        websocketApi:
          id: !Ref WebSocketApi