# infrastructure/validation.yml
Resources:
  ValidationFunction:
    Type: AWS::Lambda::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      Code:
        ZipFile: |
          exports.handler = async (event) => {
            // Validación de recursos y dependencias
            const resources = event.ResourceProperties;
            try {
              // Validaciones aquí
              return { Status: 'SUCCESS' };
            } catch (error) {
              return { Status: 'FAILED', Reason: error.message };
            }
          }
      Role: !GetAtt ValidationRole.Arn

  ValidationRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole