Resources:
  LambdaSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Lambda functions
      VpcId: !Ref SpectraVPC
      SecurityGroupEgress:
        # Redis
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          CidrIp: 0.0.0.0/0
          Description: Outbound traffic to Redis
        # HTTPS para APIs y servicios AWS
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS to AWS services and APIs
        # DNS
        - IpProtocol: tcp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
          Description: DNS (TCP)
        - IpProtocol: udp
          FromPort: 53
          ToPort: 53
          CidrIp: 0.0.0.0/0
          Description: DNS (UDP)
      Tags:
        - Key: Name
          Value: ${self:custom.service}-${self:provider.stage}-lambda-sg
        - Key: Service
          Value: ${self:custom.service}
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Component
          Value: Lambda
        - Key: ManagedBy
          Value: CloudFormation

  RedisSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Redis cluster
      VpcId: !Ref SpectraVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 6379
          ToPort: 6379
          SourceSecurityGroupId: !Ref LambdaSecurityGroup
          Description: Redis access from Lambda functions
      Tags:
        - Key: Name
          Value: ${self:custom.service}-${self:provider.stage}-redis-sg
        - Key: Service
          Value: ${self:custom.service}
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Component
          Value: Redis
        - Key: ManagedBy
          Value: CloudFormation

  InternalApiSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for internal API endpoints
      VpcId: !Ref SpectraVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # Cambiado a CidrIp para evitar la dependencia circular
          Description: HTTPS from Lambda functions
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0
          Description: HTTPS outbound
      Tags:
        - Key: Name
          Value: ${self:custom.service}-${self:provider.stage}-internal-api-sg
        - Key: Service
          Value: ${self:custom.service}
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Component
          Value: InternalAPI
        - Key: ManagedBy
          Value: CloudFormation

  VPCEndpointSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for VPC Endpoints
      VpcId: !Ref SpectraVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp: 0.0.0.0/0  # Cambiado a CidrIp para evitar la dependencia circular
          Description: HTTPS from Lambda functions
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0
          Description: All outbound traffic
      Tags:
        - Key: Name
          Value: ${self:custom.service}-${self:provider.stage}-vpce-sg
        - Key: Service
          Value: ${self:custom.service}
        - Key: Environment
          Value: ${self:provider.stage}
        - Key: Component
          Value: VPCEndpoints
        - Key: ManagedBy
          Value: CloudFormation

  # Eliminar RedisSecurityGroupIngress y LambdaSecurityGroupEgress

  SGMetricsAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: ${self:custom.service}-${self:provider.stage}-sg-blocked-requests
      MetricName: BlockedRequests
      Namespace: AWS/EC2
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 100
      ComparisonOperator: GreaterThanThreshold
      AlarmActions:
        - Fn::ImportValue: ${self:custom.service}-${self:provider.stage}-high-priority-topic-arn

Outputs:
  LambdaSecurityGroupId:
    Description: ID of the Lambda Security Group
    Value: !Ref LambdaSecurityGroup
    Export:
      Name: ${self:custom.service}-${self:provider.stage}-lambda-sg-id

  RedisSecurityGroupId:
    Description: ID of the Redis Security Group
    Value: !Ref RedisSecurityGroup
    Export:
      Name: ${self:custom.service}-${self:provider.stage}-redis-sg-id

  InternalApiSecurityGroupId:
    Description: ID of the Internal API Security Group
    Value: !Ref InternalApiSecurityGroup
    Export:
      Name: ${self:custom.service}-${self:provider.stage}-internal-api-sg-id

  VPCEndpointSecurityGroupId:
    Description: ID of the VPC Endpoint Security Group
    Value: !Ref VPCEndpointSecurityGroup
    Export:
      Name: ${self:custom.service}-${self:provider.stage}-vpce-sg-id